---
- name: Install Java
  hosts: all
  tasks:
    - name: Set facts for Java 11 vars
      set_fact:
        java_home: "/opt/jdk/{{ java_jdk_version }}"
      tags: java
    - name: Upload .tar.gz file containing binaries from local storage
      copy:
        src: "{{ java_oracle_jdk_package }}"
        dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
      register: download_java_binaries
      until: download_java_binaries is succeeded
      tags: java
    - name: Ensure installation dir exists
      become: true
      file:
        state: directory
        path: "{{ java_home }}"
      tags: java
    - name: Extract java in the installation directory
      become: true
      unarchive:
        copy: false
        src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        dest: "{{ java_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ java_home }}/bin/java"
      tags:
        - java
    - name: Export environment variables
      become: true
      template:
        src: jdk.sh.j2
        dest: /etc/profile.d/jdk.sh
      tags: java

#- name: download roles ELK
#  hosts: localhost
#  tasks:
#    - name: download roles 
#      shell: ansible-galaxy install --roles-path ./roles/ -r requirements.yml      

- name: install elastic
  hosts: elasticsearch   
  tasks:  
    - name: "install elastic" 
      include_role:
        name: "elk-elasticsearch-role"

- name: install kibana
  hosts: kibana   
  tasks:  
    - name: "install kibana" 
      include_role:
        name: "elk-kibana-role"        

- name: install logstash
  hosts: logstash   
  tasks:  
    - name: "install logstash" 
      include_role:
        name: "elk-logstash-role"      